name: "Pull Request"
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # The action defaults to search for the dependency file
        # (package-lock.json or yarn.lock) in the repository root, and uses
        # its hash as a part of the cache key.
        # https://github.com/actions/setup-node#caching-packages-dependencies
        cache-dependency-path: "**/package-lock.json"
    - run: npm ci
    - run: npm run lint
